### ISSUE TITLE
Drag and drop drama with firefox

### ISSUE THREAD

**Issue by athoune** [tOkeshu/fipes#3]
Firefox open the local file after a drag and drop.

**Comment by tOkeshu** [comment]
Do you have more information on this ?
- Which application did you use to drag your file ?
- Is the bug appear in chrome too ?

**Comment by tOkeshu** [comment]
I think I finally managed to find the bug. The last commit (f3914298dc7716bc1b08a7ab2cfe9f6de21c70c6) should fix this.

I put the latest version of Fipes online  at http//fipelines.org tell me if you encounter the bug again :)
